<?php

namespace ContainerScc58Ro;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TSNkGqcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TSNkGqc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TSNkGqc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoriesBdd' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'gameRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'categoriesBdd' => 'App\\Repository\\CategoryRepository',
            'gameRepository' => 'App\\Repository\\GameRepository',
            'paginator' => '?',
        ]);
    }
}
