<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG8FgEIi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG8FgEIi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG8FgEIi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG8FgEIi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG8FgEIi\App_KernelDevDebugContainer([
    'container.build_hash' => 'G8FgEIi',
    'container.build_id' => 'a512a629',
    'container.build_time' => 1606154072,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG8FgEIi');
